
name: dpe
channels:
  - conda-forge
dependencies:
  - python=3.8
  - pip
  - numpy>=1.7
  - scipy
  - pandas
  - scikit-learn
  - xlrd
  - lmfit>=0.9
  # - emcee
  # - corner
  - statsmodels
  # - dill
  - joblib>=0.13
  - psutil
  # - h5py
  # - numexpr
  - tqdm
  - pytest
  # - scikit-plot
  - matplotlib>=3.3
  - seaborn
  # - pip:
  #   - KDEpy
    # - fastkde
