
name: dpe
channels:
  - conda-forge
dependencies:
  - python=3.7
  # - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  #- matplotlib
  #- seaborn
  - lmfit
  - emcee
  # - corner
  - statsmodels
  # - dill
  - joblib>=0.13
  - psutil
  # - h5py
  # - numexpr
  - tqdm
