
name: dpe
channels:
  - conda-forge
dependencies:
  - python=3.8
  # - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - xlrd
  - scikit-plot
  - matplotlib>=3.3
  - seaborn
  - lmfit
  - emcee
  - corner
  - statsmodels
  # - dill
  - joblib>=0.13
  - psutil
  # - h5py
  # - numexpr
  - tqdm
